name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: |
          pip install pillow
          echo "print('free cliff')" > test.py
          python test.py
          
          git config --local user.name "ant5ant kind and virtuous"
          cd heads
          git add *.png
          git commit -am "bee4bee hacked gameherobrines acc"
          git push
