name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          pip install pillow
          echo "from PIL import Image, ImageDraw"                                     >> test.py
          echo "import os"                                                            >> test.py
          echo "for f in os.listdir():"                                               >> test.py
          echo "  if(f[-4:] == '.png' and os.path.isfile(f)):"                        >> test.py
          echo "    os.rename(f, f.lower())"                                          >> test.py
          echo "    f = f.lower()"                                                    >> test.py
          echo "    im = Image.open(f)"                                               >> test.py
          echo "    l1 = im.crop((40, 8, 48, 16))"                                    >> test.py
          echo "    im = im.crop((8, 8, 16, 16))"                                     >> test.py
          echo "    im = im.convert('RGBA')"                                          >> test.py
          echo "    l1 = l1.convert('RGBA')"                                          >> test.py
          echo "    fin = Image.new('RGBA', (128, 128))"                              >> test.py
          echo "    draw = ImageDraw.Draw(fin)"                                       >> test.py
          echo "    for x in range(0, 128, 16):"                                      >> test.py
          echo "      for y in range(0, 128, 16):"                                    >> test.py
          echo "        c1 = im.getpixel((x//16, y//16))"                             >> test.py
          echo "        c2 = l1.getpixel((x//16, y//16))"                             >> test.py
          echo "        col = (int((c1[0] * (255 - c2[3]) + c2[0] * c2[3]) / 255), int((c1[1] * (255 - c2[3]) + c2[1] * c2[3]) / 255), int((c1[2] * (255 - c2[3]) + c2[2] * c2[3]) / 255), int(255 - ((255 - c1[3]) * (255 - c2[3]) / 255)))">> test.py
          echo "        draw.rectangle((x, y, x+16, y+16), fill=col)"                 >> test.py
          echo "    fin.save(('heads/'+f).lower(), format='PNG')"                     >> test.py
          
          python test.py
          
          git config --local user.name "ant5ant kind and virtuous"
          cd heads
          git add *.png
          git commit -am "generated heads & lowercased skins. (freecliff <3)"
          git push
